name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: SteamToolPlus.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 安装 .NET Core 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 设置 MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: 还原
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: 编译
      shell: cmd
      run: |
        打包.bat

    - name: 上传程序
      uses: actions/upload-artifact@v4
      with:
        name: SteamToolPlus-${{ matrix.configuration }}-Build
        path: |
          PublishOutput\SteamToolPlus.exe
          PublishOutput\SteamToolPlus.pdb

    - name: 上传资源文件夹
      uses: actions/upload-artifact@v4
      with:
        name: SteamToolPlus-${{ matrix.configuration }}-Resources
        path: |
          Resources
        


    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    #- name: Upload build artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: MSIX Package
    #    path: ${{ env.Wap_Project_Directory }}\AppPackages
